//
// Autogenerated by Thrift Compiler (0.9.3)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = module.exports = {};
User = module.exports.User = function(args) {
  this.uid = null;
  this.uname = null;
  this.usex = null;
  this.uage = null;
  if (args) {
    if (args.uid !== undefined && args.uid !== null) {
      this.uid = args.uid;
    }
    if (args.uname !== undefined && args.uname !== null) {
      this.uname = args.uname;
    }
    if (args.usex !== undefined && args.usex !== null) {
      this.usex = args.usex;
    }
    if (args.uage !== undefined && args.uage !== null) {
      this.uage = args.uage;
    }
  }
};
User.prototype = {};
User.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.uid = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.uname = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.BOOL) {
        this.usex = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.I16) {
        this.uage = input.readI16();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

User.prototype.write = function(output) {
  output.writeStructBegin('User');
  if (this.uid !== null && this.uid !== undefined) {
    output.writeFieldBegin('uid', Thrift.Type.STRING, 1);
    output.writeString(this.uid);
    output.writeFieldEnd();
  }
  if (this.uname !== null && this.uname !== undefined) {
    output.writeFieldBegin('uname', Thrift.Type.STRING, 2);
    output.writeString(this.uname);
    output.writeFieldEnd();
  }
  if (this.usex !== null && this.usex !== undefined) {
    output.writeFieldBegin('usex', Thrift.Type.BOOL, 3);
    output.writeBool(this.usex);
    output.writeFieldEnd();
  }
  if (this.uage !== null && this.uage !== undefined) {
    output.writeFieldBegin('uage', Thrift.Type.I16, 4);
    output.writeI16(this.uage);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

